INSERT INTO interfaces (
    id,
    status,
    direction,
    eim_interface_id,
    interface_name,
    send_app_id,
    send_app_name,
    received_app_id,
    received_app_name,
    transfer_type,
    frequency,
    technology,
    pattern,
    sla,
    priority,
    interface_status,
    remarks
) VALUES 
(
    'INT001',
    'active',
    'OUT',
    'EIM001',
    'Customer Data Sync',
    'CRM001',
    'Customer Relationship Manager',
    'BIL001',
    'Billing System',
    'REST API',
    'Real-time',
    'HTTP',
    'Synchronous',
    '99.9%',
    'High',
    'active',
    NULL
);