import './globals.css';
import type { Metadata } from 'next';
import { Toaster } from "@/components/ui/toaster"

// Use system fonts instead
const systemFont = 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: systemFont }}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}